sudo: true
dist: xenial
language: node_js
node_js:
- '10'
services:
- docker
before_script:
- export TZ=Europe/Vienna
- IMAGE=keptn/github-service
- REGISTRY_USER=dirkwallerstorfer
- VERSION="$(cat version)"
- echo $VERSION
- DATE="$(date +'%Y%m%d.%H%M')"
- echo $DATE
- GIT_SHA="$(git rev-parse --short HEAD)"
- echo $GIT_SHA
- echo "$REGISTRY_PASSWORD" | docker login --username $REGISTRY_USER --password-stdin
jobs:
  include:
  - stage: develop
    if: branch = develop AND NOT type = pull_request
    script:
    - docker build . -t "${IMAGE}:${GIT_SHA}"
    - docker tag "${IMAGE}:${GIT_SHA}" "${IMAGE}:${VERSION}.${DATE}"
    - docker push "${IMAGE}:${GIT_SHA}"
    - docker push "${IMAGE}:${VERSION}.${DATE}"
  - stage: featureBugHotfix
    if: branch =~ ^feature.*$ OR branch =~ ^bug.*$ OR branch =~ ^hotfix.*$
    script:
    - TYPE="$(echo $TRAVIS_BRANCH | cut -d'/' -f1)"
    - NUMBER="$(echo $TRAVIS_BRANCH | cut -d'/' -f2)"
    - docker build . -t "${IMAGE}:${GIT_SHA}"
    - docker tag "${IMAGE}:${GIT_SHA}" "${IMAGE}:${VERSION}.${TYPE}.${NUMBER}.${DATE}"
    - docker push "${IMAGE}:${GIT_SHA}"
    - docker push "${IMAGE}:${VERSION}.${TYPE}.${NUMBER}.${DATE}"
